### ISSUE TITLE
[Resolved] Issues rendering scrollable list

### ISSUE THREAD

**Issue by evez0** [ClouddJR/DaysCounter#9]
#### Issue description
Potential Android 12 issues with listing a larger number of events per view, for the _environment A_ (see additional details) 10 or more events seems to clog up the view and the bottom one is only half-visible. This appears to occur at the time of drawing the events but is unclear as on occasion I've managed to reproduce this where the scroll works as intended instead of hiding half of the last event. This issue does not occur on _environment B_.

As you can see in the attached screenshot, to the right there is no scroll indicator.

#### Steps to reproduce the issue

1.  Create more than 10 events
2. Navigate to the tap where the events were created
3. Observe how for the given screen size the app has difficulty displaying more than 10 events. 

#### What's the expected result?
The events view future and past, should be able to display any number of events without issue.

#### What's the actual result?
For Environment A, you are not able to list more than 10 units before the view starts clogging up.

#### Additional details / screenshot
- **Environment A**
*Model:* Google Pixel 6
*OS:* Android 12
*Firmware:* DaysCounter version 2.5.5

- **Environment B**
*Model:* Samsung Galaxy S10
*OS:* Android 11
*Firmware:* DaysCounter version 2.5.5

- ![Screenshot](https://i.imgur.com/0KML8Cn.png)

**Comment by ClouddJR** [comment]
Thank you for such a detailed description!

I will look into it as soon as possible and will let you know about any updates.

**Comment by evez0** [comment]
Let me know if I can provide you with any logs. This issue has been present for the Android 12 devices I've tested.

**Comment by evez0** [comment]
This issue is resolved in the latest app release 2.6.2. Will reopen if it reappears. The design tweaks looks lit by the way. 🔥✨
